import os

import pandas as pd
import numpy as np
import functions.contract_invariants as contract_invariants
import functions.contract_pre_post as contract_pre_post
import functions.data_smells as data_smells
from helpers.enumerations import Belong, Operator, Operation, SpecialType, DataType, DerivedType, Closure, FilterType, MapOperation, MathOperator
from helpers.logger import set_logger
import pyarrow
from functions.PMML import PMMLModel

def generateWorkflow():
	#-----------------New DataProcessing-----------------
	columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df=pd.read_parquet('/wf_validation_python/data/output/columnFilter_input_dataDictionary.parquet')

	if os.path.exists('/wf_validation_python/data/output/columnFilter_output_dataDictionary.parquet'):
		columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__output_dataDictionary_df=pd.read_parquet('/wf_validation_python/data/output/columnFilter_output_dataDictionary.parquet')

	
	common_invalid_list=['inf', '-inf', 'nan']
	common_missing_list=['', '?', '.','null','none','na']
	
	
	data_smells.check_missing_invalid_value_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, 
														missing_invalid_list=[], common_missing_invalid_list=common_missing_list, field='Airline', origin_function="Column Filter")
	
	data_smells.check_missing_invalid_value_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, 
														missing_invalid_list=[], common_missing_invalid_list=common_missing_list, field='Airline ID', origin_function="Column Filter")
	
	data_smells.check_missing_invalid_value_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, 
														missing_invalid_list=[], common_missing_invalid_list=common_missing_list, field='Source airport', origin_function="Column Filter")
	
	data_smells.check_missing_invalid_value_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, 
														missing_invalid_list=[], common_missing_invalid_list=common_missing_list, field='Source airport ID', origin_function="Column Filter")
	
	data_smells.check_missing_invalid_value_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, 
														missing_invalid_list=[], common_missing_invalid_list=common_missing_list, field='Destination airport', origin_function="Column Filter")
	
	data_smells.check_missing_invalid_value_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, 
														missing_invalid_list=[], common_missing_invalid_list=common_missing_list, field='Destination airport ID', origin_function="Column Filter")
	
	data_smells.check_missing_invalid_value_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, 
														missing_invalid_list=[], common_missing_invalid_list=common_missing_list, field='Codeshare', origin_function="Column Filter")
	
	data_smells.check_missing_invalid_value_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, 
														missing_invalid_list=[], common_missing_invalid_list=common_missing_list, field='Stops', origin_function="Column Filter")
	
	data_smells.check_missing_invalid_value_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, 
														missing_invalid_list=[], common_missing_invalid_list=common_missing_list, field='Equipment', origin_function="Column Filter")
	
	data_smells.check_integer_as_floating_point(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline', origin_function="Column Filter")
	data_smells.check_types_as_string(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline', expected_type=DataType.STRING, origin_function="Column Filter")
	data_smells.check_suspect_precision(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline', origin_function="Column Filter")
	data_smells.check_date_as_datetime(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline', origin_function="Column Filter")
	data_smells.check_ambiguous_datetime_format(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline', origin_function="Column Filter")
	data_smells.check_number_string_size(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline', origin_function="Column Filter")
	data_smells.check_special_character_spacing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline', origin_function="Column Filter")
	data_smells.check_string_casing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline', origin_function="Column Filter")
	data_smells.check_intermingled_data_type(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline', origin_function="Column Filter")
	data_smells.check_contracted_text(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline', origin_function="Column Filter")
	data_smells.check_abbreviation_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline', origin_function="Column Filter")
	data_smells.check_syntactic_synonym(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline', origin_function="Column Filter")
	data_smells.check_ambiguous_value(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline', origin_function="Column Filter")
	data_smells.check_separating_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, decimal_sep='.',  field='Airline', origin_function="Column Filter")
			
	data_smells.check_integer_as_floating_point(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline ID', origin_function="Column Filter")
	data_smells.check_types_as_string(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline ID', expected_type=DataType.STRING, origin_function="Column Filter")
	data_smells.check_suspect_precision(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline ID', origin_function="Column Filter")
	data_smells.check_date_as_datetime(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline ID', origin_function="Column Filter")
	data_smells.check_ambiguous_datetime_format(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline ID', origin_function="Column Filter")
	data_smells.check_number_string_size(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline ID', origin_function="Column Filter")
	data_smells.check_special_character_spacing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline ID', origin_function="Column Filter")
	data_smells.check_string_casing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline ID', origin_function="Column Filter")
	data_smells.check_intermingled_data_type(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline ID', origin_function="Column Filter")
	data_smells.check_contracted_text(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline ID', origin_function="Column Filter")
	data_smells.check_abbreviation_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline ID', origin_function="Column Filter")
	data_smells.check_syntactic_synonym(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline ID', origin_function="Column Filter")
	data_smells.check_ambiguous_value(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Airline ID', origin_function="Column Filter")
	data_smells.check_separating_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, decimal_sep='.',  field='Airline ID', origin_function="Column Filter")
			
	data_smells.check_integer_as_floating_point(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport', origin_function="Column Filter")
	data_smells.check_types_as_string(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport', expected_type=DataType.STRING, origin_function="Column Filter")
	data_smells.check_suspect_precision(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport', origin_function="Column Filter")
	data_smells.check_date_as_datetime(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport', origin_function="Column Filter")
	data_smells.check_ambiguous_datetime_format(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport', origin_function="Column Filter")
	data_smells.check_number_string_size(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport', origin_function="Column Filter")
	data_smells.check_special_character_spacing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport', origin_function="Column Filter")
	data_smells.check_string_casing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport', origin_function="Column Filter")
	data_smells.check_intermingled_data_type(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport', origin_function="Column Filter")
	data_smells.check_contracted_text(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport', origin_function="Column Filter")
	data_smells.check_abbreviation_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport', origin_function="Column Filter")
	data_smells.check_syntactic_synonym(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport', origin_function="Column Filter")
	data_smells.check_ambiguous_value(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport', origin_function="Column Filter")
	data_smells.check_separating_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, decimal_sep='.',  field='Source airport', origin_function="Column Filter")
			
	data_smells.check_integer_as_floating_point(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport ID', origin_function="Column Filter")
	data_smells.check_types_as_string(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport ID', expected_type=DataType.STRING, origin_function="Column Filter")
	data_smells.check_suspect_precision(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport ID', origin_function="Column Filter")
	data_smells.check_date_as_datetime(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport ID', origin_function="Column Filter")
	data_smells.check_ambiguous_datetime_format(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport ID', origin_function="Column Filter")
	data_smells.check_number_string_size(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport ID', origin_function="Column Filter")
	data_smells.check_special_character_spacing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport ID', origin_function="Column Filter")
	data_smells.check_string_casing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport ID', origin_function="Column Filter")
	data_smells.check_intermingled_data_type(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport ID', origin_function="Column Filter")
	data_smells.check_contracted_text(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport ID', origin_function="Column Filter")
	data_smells.check_abbreviation_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport ID', origin_function="Column Filter")
	data_smells.check_syntactic_synonym(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport ID', origin_function="Column Filter")
	data_smells.check_ambiguous_value(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Source airport ID', origin_function="Column Filter")
	data_smells.check_separating_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, decimal_sep='.',  field='Source airport ID', origin_function="Column Filter")
			
	data_smells.check_integer_as_floating_point(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport', origin_function="Column Filter")
	data_smells.check_types_as_string(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport', expected_type=DataType.STRING, origin_function="Column Filter")
	data_smells.check_suspect_precision(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport', origin_function="Column Filter")
	data_smells.check_date_as_datetime(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport', origin_function="Column Filter")
	data_smells.check_ambiguous_datetime_format(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport', origin_function="Column Filter")
	data_smells.check_number_string_size(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport', origin_function="Column Filter")
	data_smells.check_special_character_spacing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport', origin_function="Column Filter")
	data_smells.check_string_casing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport', origin_function="Column Filter")
	data_smells.check_intermingled_data_type(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport', origin_function="Column Filter")
	data_smells.check_contracted_text(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport', origin_function="Column Filter")
	data_smells.check_abbreviation_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport', origin_function="Column Filter")
	data_smells.check_syntactic_synonym(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport', origin_function="Column Filter")
	data_smells.check_ambiguous_value(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport', origin_function="Column Filter")
	data_smells.check_separating_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, decimal_sep='.',  field='Destination airport', origin_function="Column Filter")
			
	data_smells.check_integer_as_floating_point(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport ID', origin_function="Column Filter")
	data_smells.check_types_as_string(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport ID', expected_type=DataType.STRING, origin_function="Column Filter")
	data_smells.check_suspect_precision(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport ID', origin_function="Column Filter")
	data_smells.check_date_as_datetime(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport ID', origin_function="Column Filter")
	data_smells.check_ambiguous_datetime_format(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport ID', origin_function="Column Filter")
	data_smells.check_number_string_size(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport ID', origin_function="Column Filter")
	data_smells.check_special_character_spacing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport ID', origin_function="Column Filter")
	data_smells.check_string_casing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport ID', origin_function="Column Filter")
	data_smells.check_intermingled_data_type(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport ID', origin_function="Column Filter")
	data_smells.check_contracted_text(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport ID', origin_function="Column Filter")
	data_smells.check_abbreviation_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport ID', origin_function="Column Filter")
	data_smells.check_syntactic_synonym(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport ID', origin_function="Column Filter")
	data_smells.check_ambiguous_value(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Destination airport ID', origin_function="Column Filter")
	data_smells.check_separating_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, decimal_sep='.',  field='Destination airport ID', origin_function="Column Filter")
			
	data_smells.check_integer_as_floating_point(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Codeshare', origin_function="Column Filter")
	data_smells.check_types_as_string(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Codeshare', expected_type=DataType.STRING, origin_function="Column Filter")
	data_smells.check_suspect_precision(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Codeshare', origin_function="Column Filter")
	data_smells.check_date_as_datetime(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Codeshare', origin_function="Column Filter")
	data_smells.check_ambiguous_datetime_format(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Codeshare', origin_function="Column Filter")
	data_smells.check_number_string_size(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Codeshare', origin_function="Column Filter")
	data_smells.check_special_character_spacing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Codeshare', origin_function="Column Filter")
	data_smells.check_string_casing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Codeshare', origin_function="Column Filter")
	data_smells.check_intermingled_data_type(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Codeshare', origin_function="Column Filter")
	data_smells.check_contracted_text(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Codeshare', origin_function="Column Filter")
	data_smells.check_abbreviation_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Codeshare', origin_function="Column Filter")
	data_smells.check_syntactic_synonym(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Codeshare', origin_function="Column Filter")
	data_smells.check_ambiguous_value(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Codeshare', origin_function="Column Filter")
	data_smells.check_separating_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, decimal_sep='.',  field='Codeshare', origin_function="Column Filter")
			
	data_smells.check_integer_as_floating_point(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Stops', origin_function="Column Filter")
	data_smells.check_types_as_string(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Stops', expected_type=DataType.STRING, origin_function="Column Filter")
	data_smells.check_suspect_precision(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Stops', origin_function="Column Filter")
	data_smells.check_date_as_datetime(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Stops', origin_function="Column Filter")
	data_smells.check_ambiguous_datetime_format(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Stops', origin_function="Column Filter")
	data_smells.check_number_string_size(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Stops', origin_function="Column Filter")
	data_smells.check_special_character_spacing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Stops', origin_function="Column Filter")
	data_smells.check_string_casing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Stops', origin_function="Column Filter")
	data_smells.check_intermingled_data_type(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Stops', origin_function="Column Filter")
	data_smells.check_contracted_text(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Stops', origin_function="Column Filter")
	data_smells.check_abbreviation_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Stops', origin_function="Column Filter")
	data_smells.check_syntactic_synonym(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Stops', origin_function="Column Filter")
	data_smells.check_ambiguous_value(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Stops', origin_function="Column Filter")
	data_smells.check_separating_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, decimal_sep='.',  field='Stops', origin_function="Column Filter")
			
	data_smells.check_integer_as_floating_point(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Equipment', origin_function="Column Filter")
	data_smells.check_types_as_string(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Equipment', expected_type=DataType.STRING, origin_function="Column Filter")
	data_smells.check_suspect_precision(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Equipment', origin_function="Column Filter")
	data_smells.check_date_as_datetime(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Equipment', origin_function="Column Filter")
	data_smells.check_ambiguous_datetime_format(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Equipment', origin_function="Column Filter")
	data_smells.check_number_string_size(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Equipment', origin_function="Column Filter")
	data_smells.check_special_character_spacing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Equipment', origin_function="Column Filter")
	data_smells.check_string_casing(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Equipment', origin_function="Column Filter")
	data_smells.check_intermingled_data_type(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Equipment', origin_function="Column Filter")
	data_smells.check_contracted_text(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Equipment', origin_function="Column Filter")
	data_smells.check_abbreviation_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Equipment', origin_function="Column Filter")
	data_smells.check_syntactic_synonym(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Equipment', origin_function="Column Filter")
	data_smells.check_ambiguous_value(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, field='Equipment', origin_function="Column Filter")
	data_smells.check_separating_consistency(data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df, decimal_sep='.',  field='Equipment', origin_function="Column Filter")
			
	
	field_list_columnFilter_PRE_field_range=['Airline', 'Airline ID', 'Source airport', 'Source airport ID', 'Destination airport', 'Destination airport ID', 'Codeshare', 'Stops', 'Equipment']
	if contract_pre_post.check_field_range(fields=field_list_columnFilter_PRE_field_range,
								data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df,
								belong_op=Belong(0), origin_function="Column Filter"):
		print('PRECONDITION Column Filter(Airline, Airline ID, Source airport, Source airport ID, Destination airport, Destination airport ID, Codeshare, Stops, Equipment) VALIDATED')
	else:
		print('PRECONDITION Column Filter(Airline, Airline ID, Source airport, Source airport ID, Destination airport, Destination airport ID, Codeshare, Stops, Equipment) NOT VALIDATED')
	
	
	field_list_columnFilter_POST_field_range=['Airline', 'Airline ID', 'Source airport', 'Source airport ID', 'Destination airport', 'Destination airport ID', 'Codeshare', 'Stops', 'Equipment']
	if contract_pre_post.check_field_range(fields=field_list_columnFilter_POST_field_range,
								data_dictionary=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__output_dataDictionary_df,
								belong_op=Belong(0), origin_function="Column Filter"):
		print('POSTCONDITION Column Filter(Airline, Airline ID, Source airport, Source airport ID, Destination airport, Destination airport ID, Codeshare, Stops, Equipment) VALIDATED')
	else:
		print('POSTCONDITION Column Filter(Airline, Airline ID, Source airport, Source airport ID, Destination airport, Destination airport ID, Codeshare, Stops, Equipment) NOT VALIDATED')
	
	
	columns_list_columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__INV_condition = ['Airline', 'Airline ID', 'Source airport', 'Source airport ID', 'Destination airport', 'Destination airport ID', 'Codeshare', 'Stops', 'Equipment']
	
	if contract_invariants.check_inv_filter_columns(data_dictionary_in=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__input_dataDictionary_df,
							data_dictionary_out=columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__output_dataDictionary_df,
							columns=columns_list_columnFilter_Airline_Airline_ID_Source_airport_Source_airport_ID_Destination_airport_Destination_airport_ID_Codeshare_Stops_Equipment__INV_condition,
							belong_op=Belong(1), origin_function="Column Filter"):
		print('INVARIANT Column Filter(Airline, Airline ID, Source airport, Source airport ID, Destination airport, Destination airport ID, Codeshare, Stops, Equipment) VALIDATED')
	else:
		print('INVARIANT Column Filter(Airline, Airline ID, Source airport, Source airport ID, Destination airport, Destination airport ID, Codeshare, Stops, Equipment) NOT VALIDATED')
	
	
	
	
	
	
set_logger("contracts")
generateWorkflow()
